//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loris.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BASERES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BASERES() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Loris.Resources.BASERES", typeof(BASERES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissão de acesso.
        /// </summary>
        public static string lbl_access_permission {
            get {
                return ResourceManager.GetString("lbl_access_permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administração.
        /// </summary>
        public static string lbl_administration {
            get {
                return ResourceManager.GetString("lbl_administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos.
        /// </summary>
        public static string lbl_all {
            get {
                return ResourceManager.GetString("lbl_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Média.
        /// </summary>
        public static string lbl_average {
            get {
                return ResourceManager.GetString("lbl_average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso total.
        /// </summary>
        public static string lbl_can_all {
            get {
                return ResourceManager.GetString("lbl_can_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pode criar.
        /// </summary>
        public static string lbl_can_create {
            get {
                return ResourceManager.GetString("lbl_can_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pode apagar.
        /// </summary>
        public static string lbl_can_delete {
            get {
                return ResourceManager.GetString("lbl_can_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pode ler.
        /// </summary>
        public static string lbl_can_read {
            get {
                return ResourceManager.GetString("lbl_can_read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pode gerar relatório.
        /// </summary>
        public static string lbl_can_report {
            get {
                return ResourceManager.GetString("lbl_can_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pode atualizar.
        /// </summary>
        public static string lbl_can_update {
            get {
                return ResourceManager.GetString("lbl_can_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string lbl_cancel {
            get {
                return ResourceManager.GetString("lbl_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar a senha.
        /// </summary>
        public static string lbl_change_pwd {
            get {
                return ResourceManager.GetString("lbl_change_pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechar.
        /// </summary>
        public static string lbl_close {
            get {
                return ResourceManager.GetString("lbl_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string lbl_code {
            get {
                return ResourceManager.GetString("lbl_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme a nova senha.
        /// </summary>
        public static string lbl_confirm_new_pwd {
            get {
                return ResourceManager.GetString("lbl_confirm_new_pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar.
        /// </summary>
        public static string lbl_create {
            get {
                return ResourceManager.GetString("lbl_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dias.
        /// </summary>
        public static string lbl_days {
            get {
                return ResourceManager.GetString("lbl_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar.
        /// </summary>
        public static string lbl_delete {
            get {
                return ResourceManager.GetString("lbl_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string lbl_description {
            get {
                return ResourceManager.GetString("lbl_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dicionário.
        /// </summary>
        public static string lbl_dictionary {
            get {
                return ResourceManager.GetString("lbl_dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço de e-mail.
        /// </summary>
        public static string lbl_email_address {
            get {
                return ResourceManager.GetString("lbl_email_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        public static string lbl_enter {
            get {
                return ResourceManager.GetString("lbl_enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo informado já está em uso!.
        /// </summary>
        public static string lbl_field_unique_violation {
            get {
                return ResourceManager.GetString("lbl_field_unique_violation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esqueceu a senha.
        /// </summary>
        public static string lbl_forgot_password {
            get {
                return ResourceManager.GetString("lbl_forgot_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerar chave de segurança.
        /// </summary>
        public static string lbl_gen_security_key {
            get {
                return ResourceManager.GetString("lbl_gen_security_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alto.
        /// </summary>
        public static string lbl_high {
            get {
                return ResourceManager.GetString("lbl_high", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horas.
        /// </summary>
        public static string lbl_hours {
            get {
                return ResourceManager.GetString("lbl_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id do usuário ou e-mail.
        /// </summary>
        public static string lbl_identification {
            get {
                return ResourceManager.GetString("lbl_identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserir.
        /// </summary>
        public static string lbl_insert {
            get {
                return ResourceManager.GetString("lbl_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo.
        /// </summary>
        public static string lbl_item_add {
            get {
                return ResourceManager.GetString("lbl_item_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar.
        /// </summary>
        public static string lbl_item_del {
            get {
                return ResourceManager.GetString("lbl_item_del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string lbl_item_edt {
            get {
                return ResourceManager.GetString("lbl_item_edt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglês.
        /// </summary>
        public static string lbl_lang_english {
            get {
                return ResourceManager.GetString("lbl_lang_english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma de acesso não foi informado!.
        /// </summary>
        public static string lbl_lang_not_informed {
            get {
                return ResourceManager.GetString("lbl_lang_not_informed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Português.
        /// </summary>
        public static string lbl_lang_portuguese {
            get {
                return ResourceManager.GetString("lbl_lang_portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espanhol.
        /// </summary>
        public static string lbl_lang_spanish {
            get {
                return ResourceManager.GetString("lbl_lang_spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baixo.
        /// </summary>
        public static string lbl_low {
            get {
                return ResourceManager.GetString("lbl_low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutos.
        /// </summary>
        public static string lbl_minutes {
            get {
                return ResourceManager.GetString("lbl_minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string lbl_name {
            get {
                return ResourceManager.GetString("lbl_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova senha.
        /// </summary>
        public static string lbl_new_password {
            get {
                return ResourceManager.GetString("lbl_new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string lbl_no {
            get {
                return ResourceManager.GetString("lbl_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum.
        /// </summary>
        public static string lbl_none {
            get {
                return ResourceManager.GetString("lbl_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha anterior.
        /// </summary>
        public static string lbl_old_password {
            get {
                return ResourceManager.GetString("lbl_old_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair.
        /// </summary>
        public static string lbl_out {
            get {
                return ResourceManager.GetString("lbl_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ler.
        /// </summary>
        public static string lbl_read {
            get {
                return ResourceManager.GetString("lbl_read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lembrar de mim.
        /// </summary>
        public static string lbl_remember_me {
            get {
                return ResourceManager.GetString("lbl_remember_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relatório.
        /// </summary>
        public static string lbl_report {
            get {
                return ResourceManager.GetString("lbl_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurso.
        /// </summary>
        public static string lbl_resource {
            get {
                return ResourceManager.GetString("lbl_resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código do recurso.
        /// </summary>
        public static string lbl_resource_code {
            get {
                return ResourceManager.GetString("lbl_resource_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição do recurso.
        /// </summary>
        public static string lbl_resource_description {
            get {
                return ResourceManager.GetString("lbl_resource_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome no dicionário de tradução.
        /// </summary>
        public static string lbl_resource_dictionary {
            get {
                return ResourceManager.GetString("lbl_resource_dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursos.
        /// </summary>
        public static string lbl_resources {
            get {
                return ResourceManager.GetString("lbl_resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Função/Papel.
        /// </summary>
        public static string lbl_role {
            get {
                return ResourceManager.GetString("lbl_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da função.
        /// </summary>
        public static string lbl_role_name {
            get {
                return ResourceManager.GetString("lbl_role_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funções/Papéis.
        /// </summary>
        public static string lbl_roles {
            get {
                return ResourceManager.GetString("lbl_roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string lbl_save {
            get {
                return ResourceManager.GetString("lbl_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segundos.
        /// </summary>
        public static string lbl_secounds {
            get {
                return ResourceManager.GetString("lbl_secounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chave de segurança.
        /// </summary>
        public static string lbl_security_key {
            get {
                return ResourceManager.GetString("lbl_security_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione.
        /// </summary>
        public static string lbl_select {
            get {
                return ResourceManager.GetString("lbl_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severo.
        /// </summary>
        public static string lbl_severe {
            get {
                return ResourceManager.GetString("lbl_severe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema.
        /// </summary>
        public static string lbl_system {
            get {
                return ResourceManager.GetString("lbl_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema escuro.
        /// </summary>
        public static string lbl_theme_dark {
            get {
                return ResourceManager.GetString("lbl_theme_dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema claro.
        /// </summary>
        public static string lbl_theme_light {
            get {
                return ResourceManager.GetString("lbl_theme_light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar.
        /// </summary>
        public static string lbl_to_confirm {
            get {
                return ResourceManager.GetString("lbl_to_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indefinido.
        /// </summary>
        public static string lbl_undefined {
            get {
                return ResourceManager.GetString("lbl_undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualizar.
        /// </summary>
        public static string lbl_update {
            get {
                return ResourceManager.GetString("lbl_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        public static string lbl_user {
            get {
                return ResourceManager.GetString("lbl_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string lbl_user_email {
            get {
                return ResourceManager.GetString("lbl_user_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificação.
        /// </summary>
        public static string lbl_user_external_id {
            get {
                return ResourceManager.GetString("lbl_user_external_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        public static string lbl_user_language {
            get {
                return ResourceManager.GetString("lbl_user_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apelido.
        /// </summary>
        public static string lbl_user_nickname {
            get {
                return ResourceManager.GetString("lbl_user_nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota/Observação.
        /// </summary>
        public static string lbl_user_note {
            get {
                return ResourceManager.GetString("lbl_user_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string lbl_user_pwd {
            get {
                return ResourceManager.GetString("lbl_user_pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuários.
        /// </summary>
        public static string lbl_users {
            get {
                return ResourceManager.GetString("lbl_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string lbl_yes {
            get {
                return ResourceManager.GetString("lbl_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário bloqueado! Solicite o desbloqueio com o administrador..
        /// </summary>
        public static string msg_blocked_access {
            get {
                return ResourceManager.GetString("msg_blocked_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente apagar o(s) registro(s) selecionado(s)?.
        /// </summary>
        public static string msg_conf_delete_record {
            get {
                return ResourceManager.GetString("msg_conf_delete_record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente sair do sistema?.
        /// </summary>
        public static string msg_conf_sair_sistema {
            get {
                return ResourceManager.GetString("msg_conf_sair_sistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo de configuração não foi informado!.
        /// </summary>
        public static string msg_config_file_not_informed {
            get {
                return ResourceManager.GetString("msg_config_file_not_informed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O acesso ao usuário ao sistema está desabilitado.
        /// </summary>
        public static string msg_disabled_access {
            get {
                return ResourceManager.GetString("msg_disabled_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ser informado!.
        /// </summary>
        public static string msg_field_not_informed {
            get {
                return ResourceManager.GetString("msg_field_not_informed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível atualizar pois o ID fornecido não corresponde ao objeto passado!.
        /// </summary>
        public static string msg_id_diff_obj {
            get {
                return ResourceManager.GetString("msg_id_diff_obj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID (identificador) deve ser fornecido.
        /// </summary>
        public static string msg_id_must_be_provided {
            get {
                return ResourceManager.GetString("msg_id_must_be_provided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ter entre {2} e {1} caracteres!.
        /// </summary>
        public static string msg_invalid_field {
            get {
                return ResourceManager.GetString("msg_invalid_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato do e-mail está inválido!.
        /// </summary>
        public static string msg_invalid_format_email {
            get {
                return ResourceManager.GetString("msg_invalid_format_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O login ou a senha digitada está incorreta. Por favor, tente novamente..
        /// </summary>
        public static string msg_invalid_login {
            get {
                return ResourceManager.GetString("msg_invalid_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nova senha fornecida é inválida! Forneça uma senha que respeite as regras de senha e que seja diferente da senha antiga..
        /// </summary>
        public static string msg_invalid_new_pwd {
            get {
                return ResourceManager.GetString("msg_invalid_new_pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A informação fornecida para realização da consulta é inválida!.
        /// </summary>
        public static string msg_invalid_parameter {
            get {
                return ResourceManager.GetString("msg_invalid_parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nova senha não confere com sua confirmação!.
        /// </summary>
        public static string msg_invalid_pwd_confirm {
            get {
                return ResourceManager.GetString("msg_invalid_pwd_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificação do usuário e/ou senha inválidos!.
        /// </summary>
        public static string msg_invalid_user_pwd {
            get {
                return ResourceManager.GetString("msg_invalid_user_pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O login foi realizado com sucesso!.
        /// </summary>
        public static string msg_loggin_sucess {
            get {
                return ResourceManager.GetString("msg_loggin_sucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login do usuário não foi informado!.
        /// </summary>
        public static string msg_login_not_informed {
            get {
                return ResourceManager.GetString("msg_login_not_informed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login do usuário inválido ou vencido. Favor logar novamente!.
        /// </summary>
        public static string msg_not_logged {
            get {
                return ResourceManager.GetString("msg_not_logged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um registro para apagar!.
        /// </summary>
        public static string msg_one_record_to_delete {
            get {
                return ResourceManager.GetString("msg_one_record_to_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um registro para editar!.
        /// </summary>
        public static string msg_one_record_to_edit {
            get {
                return ResourceManager.GetString("msg_one_record_to_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha fornecida está expirada!.
        /// </summary>
        public static string msg_password_expired {
            get {
                return ResourceManager.GetString("msg_password_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha foi alterada com sucesso!.
        /// </summary>
        public static string msg_pwd_changed {
            get {
                return ResourceManager.GetString("msg_pwd_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A chave foi gerada com sucesso e enviada para o e-mail cadastrado no sistema..
        /// </summary>
        public static string msg_pwd_key_generated {
            get {
                return ResourceManager.GetString("msg_pwd_key_generated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível apagar o registro!.
        /// </summary>
        public static string msg_record_delete {
            get {
                return ResourceManager.GetString("msg_record_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível inserir o registro!.
        /// </summary>
        public static string msg_record_insert {
            get {
                return ResourceManager.GetString("msg_record_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro atualizado com sucesso!.
        /// </summary>
        public static string msg_record_saved {
            get {
                return ResourceManager.GetString("msg_record_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível atualizar o registro!.
        /// </summary>
        public static string msg_record_update {
            get {
                return ResourceManager.GetString("msg_record_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servidor indisponível. Aguarde alguns instantes e tente novamente!.
        /// </summary>
        public static string msg_server_unavailable {
            get {
                return ResourceManager.GetString("msg_server_unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sessão não é mais válida. Faça login novamente na aplicação!.
        /// </summary>
        public static string msg_session_login_invalid {
            get {
                return ResourceManager.GetString("msg_session_login_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aconteceu um erro no sistema! Informe esse ID para o administrador: {0}.
        /// </summary>
        public static string msg_system_error {
            get {
                return ResourceManager.GetString("msg_system_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione &quot;Logout&quot; abaixo se você estiver pronto para encerrar sua sessão atual..
        /// </summary>
        public static string msg_system_out {
            get {
                return ResourceManager.GetString("msg_system_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível gerar a mensagem, template {0} não encontrado!.
        /// </summary>
        public static string msg_template_not_found {
            get {
                return ResourceManager.GetString("msg_template_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário bloqueado por várias tentativas de acesso.
        /// </summary>
        public static string msg_user_blocked_mult_access {
            get {
                return ResourceManager.GetString("msg_user_blocked_mult_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário sem acesso ao recurso solicitado!.
        /// </summary>
        public static string msg_user_not_authorized {
            get {
                return ResourceManager.GetString("msg_user_not_authorized", resourceCulture);
            }
        }
    }
}
